const utils = require('./utils');

class PrivacyPolicy {
    addLists(lists) {
        this.tosdrList = lists.tosdr;
        this.polisisList = lists.polisis;

        this.addDuplicateRulesForParents(this.tosdrList);
        this.addDuplicateRulesForParents(this.polisisList);
    }

    getScoreForUrl(url) {
        const hostname = utils.extractHostFromURL(url);
        const domain = utils.getDomain(url);
        const parent = utils.findParent(hostname.split('.'));

        // prefer tosdr data because that's generated by humans
        let privacyData = this.tosdrList[parent] || this.tosdrList[domain] || this.tosdrList[hostname];

        if (!privacyData) {
            privacyData = this.polisisList[parent] || this.polisisList[domain] || this.polisisList[hostname];
        }

        if (privacyData) {
            return privacyData.score;
        }
    }

    getReasonsForUrl(url) {
        const hostname = utils.extractHostFromURL(url);
        const domain = utils.getDomain(url);
        const parent = utils.findParent(hostname.split('.'));

        const tosdrData = this.tosdrList[parent] || this.tosdrList[domain] || this.tosdrList[hostname];

        const polisisData = this.polisisList[parent] || this.polisisList[domain] || this.polisisList[hostname];

        return {
            tosdr: tosdrData || {},
            polisis: polisisData || {},
        };
    }

    addDuplicateRulesForParents(list) {
        Object.keys(list).forEach((hostname) => {
            const parentEntity = utils.findParent(hostname.split('.'));

            if (parentEntity && !list[parentEntity]) {
                list[parentEntity] = list[hostname];
            }
        });
    }
}

module.exports = new PrivacyPolicy();
