language: node_js
node_js:
    - 10
cache:
    npm: true
jobs:
    include:
        - name: "Stable Chrome integration tests"
          env: CHROME_CHANNEL=stable
          addons:
              chrome: stable
        - name: "Beta Chrome integration tests"
          env: CHROME_CHANNEL=beta
          addons:
              chrome: beta
before_script:
    - npm install -g grunt-cli
script:
    - npm run test-ci
