/**
 * Generates shared/js/ui/base/locale-resources.js from the contents of the
 * shared/locales directory. The generated file is committed, and rebuilt on
 * every build so that it can never drift from the locale files.
 */
import path from 'node:path';
import { listVisible, writeIfChanged } from './fs.mjs';

const LOCALES_DIR = 'shared/locales';
const LOCALE_RESOURCES_FILE = 'shared/js/ui/base/locale-resources.js';

/** @returns {string} The generated module source. */
export function generateLocaleResources() {
    const imports = [];
    const localeObjects = {};

    for (const lang of listVisible(LOCALES_DIR)) {
        const resources = listVisible(path.join(LOCALES_DIR, lang))
            .map((file) => {
                const ns = file.slice(0, -'.json'.length);
                const importName = `${lang}${ns[0].toUpperCase()}${ns.slice(1)}`;
                imports.push(`import ${importName} from '../../../locales/${lang}/${ns}.json';`);
                return `${ns}: ${importName}`;
            })
            .join(', ');
        localeObjects[lang] = `{ ${resources} }`;
    }

    return `/**
 * This file is auto-generated by scripts/bundleLocales.mjs, based on the contents of the shared/locales directory.
 * Any manual changes in here will be overwritten on build!
 */
${imports.join('\n')}

export default {
    ${Object.entries(localeObjects)
        .map(([lang, resources]) => `${lang}: ${resources}`)
        .join(',\n    ')},
};
`;
}

/** Writes the generated module if it changed. */
export function writeLocaleResources() {
    writeIfChanged(LOCALE_RESOURCES_FILE, generateLocaleResources());
}
