/**
 * Generates shared/js/ui/base/locale-resources.js from the contents of the
 * shared/locales directory. The generated file is committed, and rebuilt on
 * every build so that it can never drift from the locale files.
 */
import fs from 'node:fs';
import path from 'node:path';
import { writeIfChanged } from './fs.mjs';

export const LOCALES_DIR = 'shared/locales';
export const LOCALE_RESOURCES_FILE = 'shared/js/ui/base/locale-resources.js';

/** @returns {string} The generated module source. */
export function generateLocaleResources() {
    const imports = [];
    const localeObjects = {};
    const locales = fs.readdirSync(LOCALES_DIR).filter((f) => !f.startsWith('.'));

    locales.forEach((lang) => {
        const namespaces = fs
            .readdirSync(path.join(LOCALES_DIR, lang))
            .filter((f) => !f.startsWith('.'))
            .map((f) => f.slice(0, f.length - 5));
        const resources = namespaces
            .map((ns) => {
                const importName = `${lang}${ns[0].toUpperCase()}${ns.slice(1)}`;
                imports.push(`import ${importName} from '../../../locales/${lang}/${ns}.json';`);
                return `${ns}: ${importName}`;
            })
            .join(', ');
        localeObjects[lang] = `{ ${resources} }`;
    });

    return `/**
 * This file is auto-generated by scripts/bundleLocales.mjs, based on the contents of the shared/locales directory.
 * Any manual changes in here will be overwritten on build!
 */
${imports.join('\n')}

export default {
    ${Object.keys(localeObjects)
        .map((lang) => `${lang}: ${localeObjects[lang]}`)
        .join(',\n    ')},
};
`;
}

/** Writes the generated module if it changed. */
export function writeLocaleResources() {
    writeIfChanged(LOCALE_RESOURCES_FILE, generateLocaleResources());
}
