name: Build

on:
  push:
    branches:
    - develop
  pull_request:

jobs:
  chrome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm run release-chrome
      - name: Check bundle size
        run: du -h build/chrome/release/chrome-release-*.zip
  firefox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm run release-firefox
      - name: Check bundle size
        run: du -sh build/firefox/release
