name: Pixel Schema Validation

on:
    push:
        branches: [main]
    pull_request:
    
jobs:
    pixel-validation:
        if: github.actor != 'dependabot[bot]'
        runs-on: ubuntu-latest
        env:
            HAS_INTERNAL_REPO: ${{ secrets.GH_RO_PAT != '' }}
        steps:
            - uses: actions/checkout@v6
            - uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: 'npm'
      
            - name: Checkout internal-github-asana-utils repo
              if: ${{ env.HAS_INTERNAL_REPO == 'true' }}
              uses: actions/checkout@v6
              with:
                  token: ${{ secrets.GH_RO_PAT }}
                  path: internal-github-asana-utils  
                  repository: duckduckgo/internal-github-asana-utils
                        
            - run: npm run install-ci
            - name: Validate pixel definitions
              run: |
                  if [ "$HAS_INTERNAL_REPO" = "true" ]; then
                      npm run validate-pixel-defs -- -g ./internal-github-asana-utils/user_map.yml
                  else
                      echo "Owner validation will be skipped because the user map is not available (expected for fork PRs)."
                      npm run validate-pixel-defs
                  fi
