name: Create Asana task for Privacy Review

on:
  pull_request:
    types: [ labeled ]

jobs:
  call-privacy-review:
    if: contains(github.event.label.name, 'privacy review')
    uses: duckduckgo/native-github-asana-sync/.github/workflows/privacy-review.yml@la-privacy-review-test
    with:
      team_name: 'Extension'
      ref: 'la-privacy-review-test'
    secrets:
      asana_pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
      github_pat: ${{ secrets.DAXMOBILE_TOKEN }}
