name: Privacy Grade

on:
    push:
        branches:
            - develop
    pull_request:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: 'npm'
            - name: Lint
              run: |
                  npm ci
                  npm run lint --workspace=packages/privacy-grade

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: 'npm'
            - name: Test
              run: |
                  npm ci
                  npm test --workspace=packages/privacy-grade
