name: Create Asana task for Privacy Review

on:
  pull_request:
    types: [ labeled ]

jobs:
  call-privacy-review:
    if: contains(github.event.label.name, 'privacy review')
    uses: duckduckgo/native-github-asana-sync/.github/workflows/privacy-review.yml@b8bffa7407e3e9f909a888e9af9704d629680d19
    with:
      team_name: 'Extension'
      ref: 'v1.5'
    secrets:
      asana_pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
      github_pat: ${{ secrets.DAXMOBILE_TOKEN }}
