name: Create Asana task for Privacy Review

on:
  pull_request:
    types: [ labeled ]

jobs:
  call-privacy-review:
    if: contains(github.event.label.name, 'privacy review')
    uses: ladamski/native-github-asana-sync/.github/workflows/privacy-review.yml@la-privacy-review-updates
    with:
      team_name: 'Extension'
      ref: 'v1.3'
    secrets:
      asana_pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
      github_pat: ${{ secrets.DAXMOBILE_TOKEN }}
